algoritmo "Desconto INSS"


var
salario, desconto:inteiro

inicio
escreval("Digite o seu salário: ")
       leia(salario)

       se (salario>=600) entao
            escreval("Seu salario é:", desconto)
           salario (<-desconto*20/100)

           senao (numero >=1200) entao
           escreval("Seu salario é:", bruto)
           <- salario*25/100




       fimse


fimalgoritmo

   liquido<- bruto-desconto
   Escreval("Salário liquido é de R$ ", liquido)

