algoritmo "semnome"
// Função :
// Autor :
// Data : 17/09/2021
// Seção de Declarações 
var
numero:inteiro

inicio
escreval("Digite a sua idade: ")
       leia(numero)

       se (numero >=60) entao
           escreval(" Você é da melhor idade")

           senao (numero <=17) entao
           escreval(" Você é menor de idade")

          senao escreval(" Maior idade")


       fimse
       
       
fimalgoritmo
